// let a = 10,
//   b = 6;

// //This will subtract
// let sum = a + b; // adds
// let differnce = a - b; // subtracts b from a
// let product = a * b; // multiply a and b
// let quotient = a / b; // divides a by b
// let remainder = a % b; // finds the remainder of a when didvided by b
// console.log("The sum of a and b is:", a + b);
// console.log("The differnce of a and b is:", a - b);
// console.log("The Product of a and b is:", a * b);
// console.log("The Quotient of a and b is:", a / b);
// console.log("The Remainder of a and b is:", a % b);

// For negative numbers here
let a = -10,
  b = 6;

//This will subtract
let sum = a + b; // adds
let differnce = a - b; // subtracts b from a
let product = a * b; // multiply a and b
let quotient = a / b; // divides a by b
let remainder = a % b; // finds the remainder of a when didvided by b
console.log("The sum of a and b is:", a + b);
console.log("The differnce of a and b is:", a - b);
console.log("The Product of a and b is:", a * b);
console.log("The Quotient of a and b is:", a / b);
console.log("The Remainder of a and b is:", a % b);
